### ISSUE TITLE
New Orthographic Variant urn:cite:hmt:msA.252r

### ISSUE THREAD

**Issue by jfacendo** [homermultitext/byzortho#1177]
URN for passage:      urn:cts:greekLit:tlg0012.tlg001.msA:19.32
Surface form  ἤ'ν
normalized form ἤν

**Comment by cjschu17** [comment]
REJECTED. Place a <sic> tag around the word instead. Not a Byzantine equivalent because of the elision mark. Typically if a word has an extra diacritical mark (breathing, accent, elision mark) or a diacritical mark that is wrong (an acute accent instead of a grave) then we tag it as <sic>. We use Byzortho when these diacritical marks are missing from the manuscript altogether. Only diaereses can be added to words and still be Byzantine equivalents.
