### ISSUE TITLE
New orthographical variant urn:cts:hmt:msA.253r οιηθεῖς 

### ISSUE THREAD

**Issue by ulalian** [homermultitext/byzortho#1452]
οιηθεῖς - wants smooth breathing mark on the iota urn:cts:greekLit:tlg5026.msA.hmt:19.2015office9_3@οιηθεῖς[1]

**Comment by cjschu17** [comment]
REJECTED. The word should be wrapped in a "sic" tag.

οιηθεῖς is related to οἴομαι; however, οιηθεῖς with a circumflex can only come from the elided feminine nominative participle, οἰηθεῖσ᾽ whereas the necessary masculine participle has a grave accent (οἰηθείς) since the subject of the sentence is Aristarchus.
